/* Auto-generated by Guing — do not edit manually */
import js from "@eslint/js";

export default [
  js.configs.recommended,
  {
    files: ["src/**/*.{ts,tsx}"],
    rules: {
      // Enforce single-DS-import invariant:
      // All UI library primitives MUST be imported via the adapter's internal entrypoint,
      // never from the raw package. This ensures the DS package remains the single source
      // of truth and developers can't accidentally bypass generated token bindings.
      "no-restricted-imports": [
        "error",
        {
          patterns: [
            {
              group: ["@mui/material", "@mui/material/*"],
              message: "Import from '../adapters/mui/internal' instead of '@mui/material' directly.",
            },
          ],
        },
      ],
    },
  },
  {
    // Adapter internal files themselves must be allowed to import from raw packages
    files: ["src/components/adapters/**/*.{ts,tsx}"],
    rules: {
      "no-restricted-imports": "off",
    },
  },
];
