/* Auto-generated by Guing — do not edit manually */
/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    extend: {
      colors: {

      },
      fontFamily: {

      },
      borderRadius: {
    "small": "var(--radius-small)",
    "medium": "var(--radius-medium)",
    "large": "var(--radius-large)",
    "round": "var(--radius-round)",
      },
      opacity: {
    "10": "var(--opacity-10)",
    "20": "var(--opacity-20)",
    "30": "var(--opacity-30)",
    "40": "var(--opacity-40)",
    "50": "var(--opacity-50)",
    "60": "var(--opacity-60)",
    "70": "var(--opacity-70)",
    "80": "var(--opacity-80)",
    "90": "var(--opacity-90)",
      },
    },
  },
};
