/* Auto-generated by Guing — do not edit manually */

import { ButtonPrimary } from '../ButtonPrimary/ButtonPrimary';
import { ButtonOutline } from '../ButtonOutline/ButtonOutline';

export const Button = {
  Primary: ButtonPrimary,
  Outline: ButtonOutline,
};

export { ButtonPrimary, ButtonOutline };
