/* Auto-generated by Guing — do not edit manually */

import { ButtonOutline } from '../ButtonOutline/ButtonOutline';
import { ButtonPrimary } from '../ButtonPrimary/ButtonPrimary';

export const Button = {
  Outline: ButtonOutline,
  Primary: ButtonPrimary,
};

export { ButtonOutline, ButtonPrimary };
