/* Auto-generated by Guing — do not edit manually */

export * from './types';

export const tokens = {
  "colors": [],
  "typography": [],
  "gaps": [
    {
      "name": "Gap 2",
      "value": 2,
      "category": "Synthesized"
    },
    {
      "name": "Gap 4",
      "value": 4,
      "category": "Synthesized"
    },
    {
      "name": "Gap 8",
      "value": 8,
      "category": "Synthesized"
    },
    {
      "name": "Gap 12",
      "value": 12,
      "category": "Synthesized"
    },
    {
      "name": "Gap 16",
      "value": 16,
      "category": "Synthesized"
    },
    {
      "name": "Gap 24",
      "value": 24,
      "category": "Synthesized"
    },
    {
      "name": "Gap 32",
      "value": 32,
      "category": "Synthesized"
    },
    {
      "name": "Gap 40",
      "value": 40,
      "category": "Synthesized"
    },
    {
      "name": "Gap 48",
      "value": 48,
      "category": "Synthesized"
    },
    {
      "name": "Gap 64",
      "value": 64,
      "category": "Synthesized"
    }
  ],
  "sizes": [
    {
      "name": "Icon SM",
      "value": 16,
      "category": "Synthesized"
    },
    {
      "name": "Icon MD",
      "value": 24,
      "category": "Synthesized"
    },
    {
      "name": "Icon LG",
      "value": 32,
      "category": "Synthesized"
    },
    {
      "name": "Avatar SM",
      "value": 32,
      "category": "Synthesized"
    },
    {
      "name": "Avatar MD",
      "value": 48,
      "category": "Synthesized"
    },
    {
      "name": "Avatar LG",
      "value": 64,
      "category": "Synthesized"
    }
  ],
  "opacity": [
    {
      "name": "10",
      "opacity": 0.1,
      "category": "Synthesized"
    },
    {
      "name": "20",
      "opacity": 0.2,
      "category": "Synthesized"
    },
    {
      "name": "30",
      "opacity": 0.3,
      "category": "Synthesized"
    },
    {
      "name": "40",
      "opacity": 0.4,
      "category": "Synthesized"
    },
    {
      "name": "50",
      "opacity": 0.5,
      "category": "Synthesized"
    },
    {
      "name": "60",
      "opacity": 0.6,
      "category": "Synthesized"
    },
    {
      "name": "70",
      "opacity": 0.7,
      "category": "Synthesized"
    },
    {
      "name": "80",
      "opacity": 0.8,
      "category": "Synthesized"
    },
    {
      "name": "90",
      "opacity": 0.9,
      "category": "Synthesized"
    }
  ],
  "radius": [
    {
      "name": "Small",
      "value": 4,
      "topLeft": 4,
      "topRight": 4,
      "bottomRight": 4,
      "bottomLeft": 4,
      "category": "Synthesized"
    },
    {
      "name": "Medium",
      "value": 8,
      "topLeft": 8,
      "topRight": 8,
      "bottomRight": 8,
      "bottomLeft": 8,
      "category": "Synthesized"
    },
    {
      "name": "Large",
      "value": 16,
      "topLeft": 16,
      "topRight": 16,
      "bottomRight": 16,
      "bottomLeft": 16,
      "category": "Synthesized"
    },
    {
      "name": "Round",
      "value": 9999,
      "topLeft": 9999,
      "topRight": 9999,
      "bottomRight": 9999,
      "bottomLeft": 9999,
      "category": "Synthesized"
    }
  ],
  "elevations": [],
  "borders": []
} as any;

export const designTokens = {
  colors: {
  },
  typography: {
  },
  radius: {
    small: { topLeft: 4, topRight: 4, bottomRight: 4, bottomLeft: 4 },
    medium: { topLeft: 8, topRight: 8, bottomRight: 8, bottomLeft: 8 },
    large: { topLeft: 16, topRight: 16, bottomRight: 16, bottomLeft: 16 },
    round: { topLeft: 9999, topRight: 9999, bottomRight: 9999, bottomLeft: 9999 },
  },
  opacity: {
    token10: 0.1,
    token20: 0.2,
    token30: 0.3,
    token40: 0.4,
    token50: 0.5,
    token60: 0.6,
    token70: 0.7,
    token80: 0.8,
    token90: 0.9,
  },
  gaps: {
    gap2: 2,
    gap4: 4,
    gap8: 8,
    gap12: 12,
    gap16: 16,
    gap24: 24,
    gap32: 32,
    gap40: 40,
    gap48: 48,
    gap64: 64,
  },
  sizes: {
    iconSM: 16,
    iconMD: 24,
    iconLG: 32,
    avatarSM: 32,
    avatarMD: 48,
    avatarLG: 64,
  },
} as const;

export type DesignTokens = typeof designTokens;
export type ColorKey = keyof typeof designTokens.colors;
export type TypographyKey = keyof typeof designTokens.typography;
export type RadiusKey = keyof typeof designTokens.radius;
export type GapKey = keyof typeof designTokens.gaps;
export type SizeKey = keyof typeof designTokens.sizes;
