/* Auto-generated by Guing — do not edit manually */

import { designTokens } from '.';

// ─── CSS-variable helper ─────────────────────────────────────────────────────

/** camelKey + prefix → '--prefix-kebab-key' (splits letter/digit boundaries). */
function toCssVar(camelKey: string, prefix: string): string {
  const kebab = camelKey
    .replace(/([A-Z0-9]+)([A-Z][a-z])/g, '$1-$2')
    .replace(/([a-z])([A-Z])/g, '$1-$2')
    .replace(/([a-zA-Z])([0-9])/g, '$1-$2')
    .replace(/([0-9])([a-zA-Z])/g, '$1-$2')
    .replace(/-+/g, '-')
    .toLowerCase();
  return `${prefix}-${kebab}`;
}

// ─── Colors ─────────────────────────────────────────────────────────────────

type ColorKey = keyof typeof designTokens.colors;
/** All Figma colour tokens as CSS-variable references. */
export const colorVars = Object.fromEntries(
  (Object.keys(designTokens.colors) as ColorKey[]).map((key) => [
    key,
    `var(${toCssVar(key, '--color')})`,
  ])
) as { [K in ColorKey]: string };

/** Semantic colour CSS-variable strings (Universal Semantic Model). */
export const semanticColorVars = {
} as const;

// ─── Top-level vars object ───────────────────────────────────────────────────

/**
 * Typed CSS-variable reference object.
 * Every value is a `var(--name)` string that resolves at runtime from `tokens.css`.
 *
 * @example
 * ```tsx
 * import { vars } from '<your-design-system>';
 * <Box sx={{ backgroundColor: vars.color.actionPrimary, borderRadius: vars.radius.medium }} />
 * ```
 */
export const vars = {
  /** Semantic colour CSS-variable strings (Universal Semantic Model). */
  color:      semanticColorVars,
  /** All design-token colour CSS-variable strings. */
  colorToken: colorVars,
} as const;

export type Vars = typeof vars;
