/* AUTO-GENERATED by the deterministic component emitter. Do not edit by hand. */
import React from 'react';
import ButtonBase from '@mui/material/ButtonBase';
import CircularProgress from '@mui/material/CircularProgress';

export interface ButtonOutlineProps {
  /** Fired when the user clicks / activates the primitive. */
  onClick?: (event: React.SyntheticEvent) => void;
  /** Fired when the mouse enters. */
  onHover?: (event: React.SyntheticEvent) => void;
  /** Disable the primitive. */
  isDisabled?: boolean;

  /** Show a loading spinner. Also implies disabled. */
  isLoading?: boolean;

  /** Content rendered inside the primitive. */
  children?: React.ReactNode;

  /** Optional leading icon (React node). */
  icon?: React.ReactNode;

  /** Extra sx overrides merged on top of the manifest-driven styles. */
  sx?: Record<string, unknown>;
  /** Extra className to append. */
  className?: string;
  /** Figma variant axis: "Type" (values: "Text button" → textButton, "Icon button" → iconButton) */
  type?: 'textButton' | 'iconButton';
  /** Figma variant axis: "Size" (values: "lg" → lg, "md" → md, "sm" → sm, "xs" → xs) */
  size?: 'lg' | 'md' | 'sm' | 'xs';
  /** Figma variant axis: "Width" (values: "Compact" → compact, "Fluid/block" → fluidBlock) */
  width?: 'compact' | 'fluidBlock';
  /** Figma variant axis: "State" (values: "Default" → default, "Hover" → hover, "Focus" → focus, "Disabled" → disabled) */
  state?: 'default' | 'hover' | 'focus' | 'disabled';
}

const ButtonOutline = React.forwardRef<HTMLButtonElement, ButtonOutlineProps>(
  ({ onClick, onHover, sx, className, isDisabled, isLoading, children, icon, type = 'textButton', size = 'lg', width = 'compact', state = 'default', ...rest }, ref) => (
    <ButtonBase
      ref={ref}
      onClick={onClick}
      onMouseEnter={onHover}
      disabled={isDisabled || isLoading}
      className={className}
      {...rest}
      sx={{
        display: 'inline-flex',
        alignItems: 'center',
        justifyContent: 'center',
        boxSizing: 'border-box',
        gap: 'var(--dimension-8---0-5-rem)',
        paddingLeft: 'var(--dimension-24---1-5-rem)',
        paddingRight: 'var(--dimension-24---1-5-rem)',
        borderTopLeftRadius: 'var(--border-radius-lg)',
        borderTopRightRadius: 'var(--border-radius-lg)',
        borderBottomLeftRadius: 'var(--border-radius-lg)',
        borderBottomRightRadius: 'var(--border-radius-lg)',
        borderTopWidth: 'var(--border-width-thin)',
        borderBottomWidth: 'var(--border-width-thin)',
        borderLeftWidth: 'var(--border-width-thin)',
        borderRightWidth: 'var(--border-width-thin)',
        borderColor: 'var(--fixed-white-base)',
        letterSpacing: 'var(--body-md-letter-spacing)',
        fontSize: 'var(--body-md-font-size)',
        fontFamily: 'var(--font-family-body)',
        lineHeight: 'var(--body-md-line-height-24)',
        fontWeight: 'var(--font-weight-medium---500)',
        color: 'var(--fixed-white-base)',
        border: '0',
        cursor: 'pointer',
        '&:hover': {
          backgroundColor: 'var(--background-state-interaction-hover-white)',
        },
        '&:focus-visible': {
          effects: 'var(--background-white-base)',
        },
        ...(sx as object || {}),
      }}
    >
      {icon && <span aria-hidden="true" style={{ display: 'inline-flex' }}>{icon}</span>}
      {isLoading ? <CircularProgress size={16} color="inherit" /> : children}
    </ButtonBase>
  )
);
ButtonOutline.displayName = 'ButtonOutline';
export { ButtonOutline };
export default ButtonOutline;
