/* AUTO-GENERATED by the deterministic component emitter. Do not edit by hand. */
import React from 'react';
import type { Meta, StoryObj } from '@storybook/react';
import { Sparkles } from 'lucide-react';
import { ChipTag } from './ChipTag';

const meta: Meta<typeof ChipTag> = {
  title: 'Components/Chip/Tag',
  component: ChipTag,
  tags: ['autodocs'],
};

export default meta;

type Story = StoryObj<typeof ChipTag>;

/** Canonical render — matches the Figma Default variant. */
export const Default: Story = {};

/** Variant axis "Type" = "Gray - outline". */
export const Type_GrayOutline: Story = {
  args: {
    type: 'grayOutline',
  },
};

/** Variant axis "Type" = "Primary". */
export const Type_Primary: Story = {
  args: {
    type: 'primary',
  },
};

/** Variant axis "Type" = "Primary - outline". */
export const Type_PrimaryOutline: Story = {
  args: {
    type: 'primaryOutline',
  },
};

/** Variant axis "Size" = "sm". */
export const Size_Sm: Story = {
  args: {
    size: 'sm',
  },
};

/** Variant axis "Size" = "md". */
export const Size_Md: Story = {
  args: {
    size: 'md',
  },
};

/** Variant axis "State" = "Hover". */
export const State_Hover: Story = {
  args: {
    state: 'hover',
  },
};

/** Variant axis "State" = "Disabled". */
export const State_Disabled: Story = {
  args: {
    state: 'disabled',
  },
};

/** Variant axis "isSelected" = "True (style 1)". */
export const IsSelected_Truestyle1: Story = {
  args: {
    isSelected: 'truestyle1',
  },
};

/** Variant axis "isSelected" = "True (style 2)". */
export const IsSelected_Truestyle2: Story = {
  args: {
    isSelected: 'truestyle2',
  },
};

/** Disabled state. */
export const Disabled: Story = {
  args: {
    isDisabled: true,
  },
};

/** Rendered with a leading icon. */
export const WithIcon: Story = {
  args: {
    icon: <Sparkles size={16} />,
  },
};
