/* AUTO-GENERATED by the deterministic component emitter. Do not edit by hand. */
import React from 'react';
import Chip from '@mui/material/Chip';

export interface ChipTagProps {
  /** Fired when the user clicks / activates the primitive. */
  onClick?: (event: React.SyntheticEvent) => void;
  /** Fired when the mouse enters. */
  onHover?: (event: React.SyntheticEvent) => void;
  /** Disable the primitive. */
  isDisabled?: boolean;

  /** Optional leading icon (React node). */
  icon?: React.ReactNode;

  /** Extra sx overrides merged on top of the manifest-driven styles. */
  sx?: Record<string, unknown>;
  /** Extra className to append. */
  className?: string;
  /** Figma variant axis: "Type" (values: "Gray" → gray, "Gray - outline" → grayOutline, "Primary" → primary, "Primary - outline" → primaryOutline) */
  type?: 'gray' | 'grayOutline' | 'primary' | 'primaryOutline';
  /** Figma variant axis: "Size" (values: "xs" → xs, "sm" → sm, "md" → md) */
  size?: 'xs' | 'sm' | 'md';
  /** Figma variant axis: "State" (values: "Default" → default, "Hover" → hover, "Disabled" → disabled) */
  state?: 'default' | 'hover' | 'disabled';
  /** Figma variant axis: "isSelected" (values: "False" → no, "True (style 1)" → truestyle1, "True (style 2)" → truestyle2) */
  isSelected?: 'no' | 'truestyle1' | 'truestyle2';
}

const ChipTag = React.forwardRef<HTMLDivElement, ChipTagProps>(
  ({ onClick, onHover, sx, className, isDisabled, icon, type = 'gray', size = 'xs', state = 'default', isSelected = 'no', ...rest }, ref) => (
    <Chip
      ref={ref}
      onClick={onClick}
      onMouseEnter={onHover}
      disabled={isDisabled}
      className={className}
      variant="filled"
      {...rest}
      sx={{
        display: 'inline-flex',
        alignItems: 'center',
        justifyContent: 'center',
        boxSizing: 'border-box',
        gap: 'var(--dimension-4---0-25-rem)',
        paddingLeft: 'var(--dimension-8---0-5-rem)',
        paddingTop: 'var(--dimension-4---0-25-rem)',
        paddingRight: 'var(--dimension-8---0-5-rem)',
        paddingBottom: 'var(--dimension-4---0-25-rem)',
        borderTopLeftRadius: 'var(--border-radius-xs)',
        borderTopRightRadius: 'var(--border-radius-xs)',
        borderBottomLeftRadius: 'var(--border-radius-xs)',
        borderBottomRightRadius: 'var(--border-radius-xs)',
        backgroundColor: 'var(--background-neutral-subtle-300)',
        letterSpacing: 'var(--body-xs-letter-spacing)',
        fontSize: 'var(--body-xs-font-size)',
        fontFamily: 'var(--font-family-body)',
        lineHeight: 'var(--body-xs-line-height)',
        fontWeight: 'var(--font-weight-medium---500)',
        color: 'var(--text-neutral-subtle-100)',
        ...(sx as object || {}),
      }}
    >
      {icon}
    </Chip>
  )
);
ChipTag.displayName = 'ChipTag';
export { ChipTag };
export default ChipTag;
