/* AUTO-GENERATED by the deterministic component emitter. Do not edit by hand. */
import React from 'react';
import type { Meta, StoryObj } from '@storybook/react';
import { Sparkles } from 'lucide-react';
import { ButtonPrimary } from './ButtonPrimary';

const meta: Meta<typeof ButtonPrimary> = {
  title: 'Components/Button/Primary',
  component: ButtonPrimary,
  tags: ['autodocs'],
};

export default meta;

type Story = StoryObj<typeof ButtonPrimary>;

/** Canonical render — matches the Figma Default variant. */
export const Default: Story = {
  args: {
    children: 'Button (Primary)',
  },
};

/** Variant axis "Type" = "Icon button". */
export const Type_IconButton: Story = {
  args: {
    children: 'Button (Primary)',
    type: 'iconButton',
  },
};

/** Variant axis "Size" = "md". */
export const Size_Md: Story = {
  args: {
    children: 'Button (Primary)',
    size: 'md',
  },
};

/** Variant axis "Size" = "sm". */
export const Size_Sm: Story = {
  args: {
    children: 'Button (Primary)',
    size: 'sm',
  },
};

/** Variant axis "Size" = "xs". */
export const Size_Xs: Story = {
  args: {
    children: 'Button (Primary)',
    size: 'xs',
  },
};

/** Variant axis "Width" = "Fluid/block". */
export const Width_FluidBlock: Story = {
  args: {
    children: 'Button (Primary)',
    width: 'fluidBlock',
  },
};

/** Variant axis "State" = "Hover". */
export const State_Hover: Story = {
  args: {
    children: 'Button (Primary)',
    state: 'hover',
  },
};

/** Variant axis "State" = "Focus". */
export const State_Focus: Story = {
  args: {
    children: 'Button (Primary)',
    state: 'focus',
  },
};

/** Variant axis "State" = "Disabled". */
export const State_Disabled: Story = {
  args: {
    children: 'Button (Primary)',
    state: 'disabled',
  },
};

/** Loading state with spinner. */
export const Loading: Story = {
  args: {
    children: 'Button (Primary)',
    isLoading: true,
  },
};

/** Disabled state. */
export const Disabled: Story = {
  args: {
    children: 'Button (Primary)',
    isDisabled: true,
  },
};

/** Rendered with a leading icon. */
export const WithIcon: Story = {
  args: {
    children: 'Button (Primary)',
    icon: <Sparkles size={16} />,
  },
};
